[project]
name = "ml_networks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "oakwood-fujiken", email = "oakwood.n14.4sp@keio.jp" }
]
requires-python = ">=3.10"
dependencies = [
    "einops>=0.8.1",
    "kornia>=0.7.3",
    "numpy>=2.1",
    "omegaconf>=2.3.0",
    "pytorch-lightning>=2.4.0",
    "pytorch-optimizer>=3.4.2",
    "schedulefree>=1.4",
    "torch>=2.5",
    "torchgeometry>=0.1.2",
    "torchvision>=0.19.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipython>=8.33.0",
    "mypy>=1.15.0",
    "pytest-cov>=6.0.0",
    "ruff>=0.9.10",
]

[tool.mypy]
python_version = "3.8"
plugins = "numpy.typing.mypy_plugin"

[tool.ruff]
line-length = 120
target-version = "py38"

[tool.ruff.lint]
preview = true
select = ["ALL"]
ignore = []
fixable = ["ALL"]
unfixable = []
exclude = [".git", ".ruff_cache", ".venv",]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
preview = true

[tool.ruff.lint.isort]
known-first-party = ["pinpad"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.pydoclint]
style = 'numpy'
exclude = '\.git|\.ruff_cache|\.mypy_cache|\.venv'
